Completition and implementation - section Join Us repair
cesko-digital/web pull request #146
Opened 2021-01-31 14:48 UTC by MartinaHytychova

Fixes # .

Checklist pro nové změny: 

- [ ] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [ ] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [ ] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [ ] Veškerá logika má jednoduché pokrytí unit testy
- [ ] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [ ] Design odpovídá Figmě
- [ ] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [ ] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-02-01 14:44 UTC, tuanphungcz requested changes

2021-02-01 16:13 UTC, tuanphungcz commented
@MartinaHytychova Ještě jsem si všiml, že při breakpointu 850px, tam chybí odsazení mezi komponentama

![image](https://user-images.githubusercontent.com/16448321/106485363-cd850280-64b0-11eb-812d-d083df905814.png)

2021-02-01 16:42 UTC, tuanphungcz commented
@MartinaHytychova
Díky moc Martino! 👏

Koukal jsem jak to vypadá v Preview a vypadá to dobře. Co jsem pročetl PR, tak jsem tam narazil jen na pár drobností + na při nějakých breakpointech ty komponenty zapadnou k sobě. 

Jinak je to super a ještě jednou díky. 🙏

2021-02-01 17:33 UTC, MartinaHytychova commented
Ahoj @tuanphungcz  moc děkuji za review :) Je to můj první contributing v opensource projectu, připomínky zapracuji ještě dnes. :)

2021-02-01 21:05 UTC, MartinaHytychova commented on src/components/sections/join-us/join-us.tsx
> +      <S.Title>Zapojte se</S.Title>
Tady teď nevím jistě, je tím myšleno použití useTranslation() nebo něco jiného?

2021-02-01 22:09 UTC, tuanphungcz commented on src/components/sections/join-us/join-us.tsx
> +      <S.Title>Zapojte se</S.Title>
jo, teď jsem si uvědomil, že ty překlady jsme přidali nově a na dalších místech ještě nejsou, takže takhle to máš v pohodě.  :)

2021-02-01 22:56 UTC, MartinaHytychova commented on src/components/sections/join-us/join-us.tsx
> +      <S.Title>Zapojte se</S.Title>
dobře, děkuji :)

2021-02-01 23:02 UTC, MartinaHytychova commented
úpravy zapracovány

2021-02-03 15:19 UTC, tuanphungcz commented
@MartinaHytychova Ahoj, ještě tě poprosím vyřešení konfliktů. Díky 😊

2021-02-03 18:02 UTC, MartinaHytychova commented
@tuanphungcz  mně to tu ukazuje, že žádné konflikty už nemám, včera jsem ten jeden vyřešila :) Byly to dva importy. Tak snad to bude ok. :)

2021-02-03 18:53 UTC, MartinaHytychova commented
@tuanphungcz  mělo by být vyřešeno a squashnuto :)

2021-02-08 11:58 UTC, tuanphungcz commented
@MartinaHytychova Ahoj, vyřešili jsme už problem s deployvaním Vercelem a nyní to už prochází. Prosím,  podívej se ještě na tenhle konflikt `src/pages/index.tsx` a pak to můžem zamergovat. Díky 🙏

2021-02-08 13:50 UTC, MartinaHytychova commented
@tuanphungcz konflikt vyřešen

2021-02-08 14:42 UTC, tuanphungcz approved these changes

2021-02-08 14:43 UTC, merged