Added component for numbers
cesko-digital/web pull request #152
Opened 2021-02-13 10:35 UTC by rostaklein

Solves https://github.com/cesko-digital/web/issues/130

Checklist pro nové změny:

- [x] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [x] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [x] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [x] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [x] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-02-15 08:07 UTC, HormCodes commented
Ahoj @rostaklein, díky moc za pull request! 🙏 ... Mrknu se na to a pokud to bude všechno OK, tak zamerguji během zítřejšího dopoledne. 🙂

2021-02-15 15:48 UTC, rostaklein commented
Pokud bude v pohode tak se rad mrknu brzy i na neco dalsiho :)

2021-02-17 00:08 UTC, HormCodes requested changes
Ahoj @rostaklein ještě jednou. Moc si ceníme tvého příspěvku. Issue bohužel nebylo rozepsané a _ready na vývoj,_ takže bude potřeba pár věcí pozměnit z důvodu nekompletní specifikace, ale jinak celkově to vypadá dobře. 👍 

Konkrétně bych tě rád poprosil o: 

- Přesun komponenty do `page-components/homepage/sections` a odstranění ze Storybooku (komponenta s největší pravděpodobností bude využita jen na homepage)
- Zadefinovat `numbers` přímo do komponenty a využít překladové klíče ve tvaru `pages.homepage.sections.${type}.{value,subtitle}`

Kdyby bylo něco nejasného, tak rád dovysvětlím. Zároveň posílám preview na vizuální check na design. 

Díky ještě jednou a těším se, až budeme mít tuto sekci z homepage hotovou. 🙂

2021-02-17 16:34 UTC, HormCodes commented on src/components/numbers/styles.ts
> +    &:after {
Tuan dal ještě dobrý input, že tato část by se dala extrahovat do proměnné, aby bylo jasné, že se jedná o divider. Co myslíš? 

```typescript jsx
const sectionDivider = css`
&:after {
      content: '';
      position: absolute;
      top: 22px;
      bottom: 0;
      right: -2px;
      width: 2px;
      height: 36px;
      background-color: rgba(8, 8, 49, 0.1);
    }
`
```

2021-02-17 16:50 UTC, tjerabek requested changes
Za mě pouze dvě drobnosti, aby to sedělo k designu. Font-size popisku pod číslem nesedí a mezera mezi popiskem a číslem je příliš veliká.

2021-02-17 16:50 UTC, tjerabek commented on src/components/numbers/styles.ts
> +  margin: 24px 0 0 0;
```suggestion
  margin: 16px 0 0 0;
```

2021-02-17 16:50 UTC, tjerabek commented on src/components/numbers/styles.ts
> +  font-size: ${({ theme }) => theme.fontSizes.base}px;
`font-size` tady vychází v designu `20px`, ale v nasazení je `18px`

2021-02-18 16:52 UTC, rostaklein commented on src/components/numbers/styles.ts
> +  font-size: ${({ theme }) => theme.fontSizes.base}px;
S timto jsem trochu bojoval, jelikoz ve fontSizech zadna 20px velikost neni, tzn. pouzil jsem tu nejblizsi.

2021-02-18 16:56 UTC, rostaklein commented
Pushnul jsem zmeny, nicmene temi translation keys si vubec nejsem jistej. Neslo by (i vzhledem k dalsim pripadnym contributorum) toto nejak zjednodusit? 🤷‍♂️ Navic ted samozrejme ta komponenta s tak extremne dlouhym textem (klic prekladu) bohuzel vypada spatne :(

2021-02-22 21:27 UTC, HormCodes approved these changes
@rostaklein, díky moc za úpravy. 🙏 

Vypadá to dobře, schvaluji, vyčistím historii (+fixnu ještě default export) a poté zamerguji. 

Pokud jde o samoné překladové klíče. Napadlo tě, že si hodnoty pro testování můžeš vložit do souborů s překlady (`locale/{cs,en}/translation.json`) sám? Pokud ne, pomohla by zmínka v rámci README?

2021-02-22 21:40 UTC, merged