Implementation of project status component
cesko-digital/web pull request #166
Opened 2021-03-01 13:17 UTC by MartinaHytychova

Fixes # .

Checklist pro nové změny:

- [ ] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [ ] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [ ] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [ ] Veškerá logika má jednoduché pokrytí unit testy
- [ ] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [ ] Design odpovídá Figmě
- [ ] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [ ] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-03-01 13:53 UTC, HormCodes commented on src/components/social-media/social-media/index.tsx
> +    <S.Logo>{logo}</S.Logo>
Pokračování diskuse na Slacku ohledně nefunkčních ikon: 

Je zde více cest. Jedna (a asi ta nejlepší) je namapovat hodnotu tak, aby JSX kompilátor byl spokojený: 

```typescript jsx
const SocialMedia: React.FC<Props> = ({ logo, url, name }) => {
  const SocialIcon = logo
  return (
    <S.Container>
      <S.Logo>
        <SocialIcon /> 
      </S.Logo>
      <S.Link href={url}>{name}</S.Link>
    </S.Container>
  )
}
```

Každá komponenta je víceméně funkcí a JSX zápis tuto funkci zavolá. Tedy by i fungoval zápis `<S.Logo>{logo({})}</S.Logo>`. Některé komponenty tento případ řešili přes `renderLogo` namísto `logo`, kde bylo jasné, že se jedná o funkci při použití komponenty, ale i v její implementaci. Nicméně toto řešení vyžaduje zanoření do funkce `renderIcon: () => SlackIcon` u každého použití.

2021-03-01 14:03 UTC, HormCodes requested changes
@MartinaHytychova, mohu tě taky poprosit ještě o rebase, umístění do `src/templates/project` a vytvoření této struktury: 

```
templates
   project
      index.tsx // Stávající obsah project.tsx + použití komponenty sekce O projektu
      sections
          index.ts // Exporty
          about
              index.tsx // Prázdná sekce + stav projektu (v budoucnu bude rozšířeno)
              project-status // Tvá komponenta
```

2021-03-01 15:16 UTC, tuanphungcz reviewed
Ahoj, narazil jsem na par drobnosti jinak to vypada dobre. Jen takovy dotaz, vsiml jsem si ze ta komponenta je trochu mala na mobilu (viz screenshot). Nemeli bychom tu komponentu udelat trochu sirsi?
![image](https://user-images.githubusercontent.com/16448321/109517300-648dac00-7aa9-11eb-971e-1697b7e31f3e.png)

2021-03-01 15:16 UTC, tuanphungcz commented on src/components/social-media/social-media/styles.tsx
> +  border-bottom: 2px solid #cccccc;
Mozna bych tuto barvu pridal do palety, vsiml jsem si si ji pouzila i v jinem souboru.

2021-03-01 15:16 UTC, tuanphungcz commented on src/components/avatars/avatar/style.ts
> +
smazal bych volnou mezeru

2021-03-01 15:16 UTC, tuanphungcz commented on src/components/progress/progress/index.tsx
> +    <ProgressBar percent={percent} />{' '}
je zde treba `{' '}`?

2021-03-01 18:08 UTC, MartinaHytychova reviewed
> Ahoj, narazil jsem na par drobnosti jinak to vypada dobre. Jen takovy dotaz, vsiml jsem si ze ta komponenta je trochu mala na mobilu (viz screenshot). Nemeli bychom tu komponentu udelat trochu sirsi?
> ![image](https://user-images.githubusercontent.com/16448321/109517300-648dac00-7aa9-11eb-971e-1697b7e31f3e.png)

Jdu to ještě poupravit :)

2021-03-01 21:09 UTC, MartinaHytychova commented
> @MartinaHytychova, mohu tě taky poprosit ještě o rebase (vyřešení konfliktů), umístění do `src/templates/project` a vytvoření této struktury:
> 
> ```
> templates
>    project
>       index.tsx // Stávající obsah project.tsx + použití komponenty sekce O projektu
>       sections
>           index.ts // Exporty
>           about
>               index.tsx // Prázdná sekce + stav projektu (v budoucnu bude rozšířeno)
>               project-status // Tvá komponenta
> ```
> 
> Rád s tím případně pomohu pokud bude třeba. 🙂

Jestli tedy chápu správně:
- obsah souboru `project.tsx` přejmenovat na `index.tsx` a tam přidat navíc sekci se `Status Projektu`?
- složku `status-project`, kde mám tu komponentu mám vyjmout a přesunout ze složky `page-components`?

Mám to nějak už nachystané, jen se raději ještě ujišťuji, že to tak je. :)

2021-03-03 12:30 UTC, tjerabek requested changes
Vypadá to dobře, narazil jsem jen na pár drobností s rozestupy. A ikona `?` je trochu jiná než v designu. 

![review](https://user-images.githubusercontent.com/1576931/109806151-a4c56980-7c24-11eb-9df5-d5653cf04637.png)

2021-03-03 20:52 UTC, MartinaHytychova commented
> Vypadá to dobře, narazil jsem jen na pár drobností s rozestupy. A ikona `?` je trochu jiná než v designu.
> 
> ![review](https://user-images.githubusercontent.com/1576931/109806151-a4c56980-7c24-11eb-9df5-d5653cf04637.png)

Upraveno

2021-03-05 20:11 UTC, MartinaHytychova commented
Před dvěma dny jsem vše upravila, takže snad už bude ok :) @HormCodes @tuanphungcz @tjerabek

2021-03-07 16:34 UTC, HormCodes approved these changes
@MartinaHytychova, díky moc za pull request a úpravy. Trochu jsem komponenty a data přeskládal na základě nových změn (zároveň jsem provedl rebase a vyřešil konflikty), ale ve výsledku se nejednalo o žádné velké změny a jedná se o super práci. 

Omlouvám se, že jsem tyto změny neohlásil dopředu. Našla jsi tam ještě nějaké nezbytné úpravy?

2021-03-07 17:00 UTC, merged

2021-03-07 17:00 UTC, HormCodes commented
@MartinaHytychova, zamergoval jsem. Díky moc za pomoc! 🙏

2021-03-07 18:02 UTC, MartinaHytychova commented
@HormCodes  já jsem si dnes všimla těch konfliktů a chtěla jsem je vyřešit, ale moc děkuji za pomoc. :)