Feature: Project about section
cesko-digital/web pull request #168
Opened 2021-03-01 20:34 UTC by rostaklein

Solves https://github.com/cesko-digital/web/issues/126.

Nekolik poznamek:
1. Bohuzel vubec netusim kde mam vzit spravne klice k prekladum (vymyslim si je z hlavy). Obecne celkove preklady jsou dost pain. [Zde](https://github.com/cesko-digital/web/blob/rework/doc/translations.md) je hezky popsano jak funguji, nicmene kdybych chtel napriklad z aktualniho airtable stahnout vsechny preklady nekam do untracked slozky a podivat se jaky klice jsou tam dostupny, tak by to mooc pomohlo. Jaky je vubec plan dostat tyto stringy do Airtable? (nemam s Airtable zadne zkusenosti, ale predpokladam, ze tady zadna chytra staticka analyza kodu probihat nebude)
2. stejne tak by mega moc pomohlo mit jakz takz hotovy datovy model, v tomto pripade napriklad pro typ `Volunteer/Person/...` a pripravenej pro nej typ v `graphql-types.ts`
3. nejsem si jisty umistenim komponent v `templates` slozce, ale jelikoz nikde jinde dane komponenty pouzity nejsou, prislo mi to jako nejlepsi reseni
4. nevytvarel jsem zadne storybooky, posledne jsem je z PR mazal, tzn. rad dodelam, bude li treba

2021-03-03 20:18 UTC, HormCodes reviewed
@rostaklein díky moc za pull request a velký obdiv za rychlost. 👏 

K tvým podnětům:

1. Bohužel AirTable neumí API klíče s read-only právy, takže není možné vystavit dev přístup na překladové data. Zároveň se mi úplně nezamlouvá mít (téměř) kompletní kopii v rámci `translation.example.json` aby to nenávadělo přidávat překlady tam. Nicméně jsem objevil možnost [veřejného pohledu do tabulky s překlady](https://airtable.com/shraCQhMJdGUu1xhk), takže rovnou vystavím PR s tímto pohledem v rámci dokumentace. Překladové klíče měly být v rámci specifikace, za to se omlouvám.
2. Též mělo být součást specifikace. Tvoje definice přesně odpovídá tomu, co už máme v AirTable (rozšíření implementace ještě nezačalo). O tomto bych asi uvedl pár slov v rámci nabízeného onboardingu. 
3. Umístění až na jeden detail (viz komentář u kódu) je v pořádku. 
4. Platí pravidlo většina věcí v `src/components` by měla mít dokumentaci ve Storybooku. Níže je vlákno pro story na Avatar komponentu

Jinak to vypadá velmi dobře. Kód je srozumitelný a nebylo těžké udělat review. Přidal jsem pár věcí, ale věřím, že to nezabere moc času. Zároveň dávám request na design review.

2021-03-03 20:18 UTC, HormCodes commented on src/templates/project/project.tsx
> +              <AboutProject />
Mohu poprosit o zadefinování mock dat v rámci této komponenty pro celou stránku a odstranění použití `defaultProps`? Ať už jako konstantu nebo rovnou jako props.

2021-03-03 20:18 UTC, HormCodes commented on src/templates/project/project.tsx
> +      <Section backgroundColor={theme.colors.pebble}>
Barva celé sekce je ve Figmě bílá.

2021-03-04 08:03 UTC, tjerabek requested changes
Až na posun karty o projektu nahoru v mobilní verzi, za mě v pořádku.

2021-03-05 21:58 UTC, HormCodes approved these changes
@rostaklein, díky moc za úpravy! Během dneška jsem si ještě všiml špatného renderování avatarů při SSR, takže jsem přilepil fix v rámci čištění historie. 

Díky moc za PR, je to velmi dobře odvedená práce. Máš chuť si vzít nějaký další task? Pokud ano, máš nějaké preference nebo mohu přiřadit něco podle aktuálních priorit?

2021-03-05 22:03 UTC, merged