Our projects
cesko-digital/web pull request #170
Opened 2021-03-06 18:30 UTC by maral

Fixes #128.

Checklist pro nové změny:

- [x] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [x] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [x] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [x] Veškerá logika má jednoduché pokrytí unit testy
- [x] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [x] Design odpovídá Figmě
- [x] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [x] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-03-07 19:22 UTC, maral commented
Ještě se tam koukám tvoří nějaká druhá scroll lišta v určitých velikostech, to bude chtít ještě poladit.

2021-03-07 19:58 UTC, HormCodes requested changes
Ahoj @maral, díky moc za pull request! 👍 

Vypadá to velmi dobře. Myslím, že bude potřeba upravit padding v rámci mobilní verze, ale uvidíme zda to bude zmíněno v rámci design review. 

Kód byl srozumitelný a až na 3 maličkosti v pořádku. Můžeš se na to prosím podívat? 

Jinak se těším, až si budeme moct odškrtnout i tuto sekci, protože komponentu s největší pravděpodobností použijeme i na stránce _Detail projektu_. 🙂

2021-03-07 19:58 UTC, HormCodes commented on src/pages/index.tsx
> +          rowId
Můžeš prosím query upravit tak, aby obsahovala pouze věci, které se na stránce vykreslují? Např. odstranit `rowId`,  `lang` atd.

2021-03-07 19:58 UTC, HormCodes commented on src/page-components/homepage/sections/our-projects/styles.tsx
> +export const ProjectCard = styled(PC)`
Používání zkratek není ideální. Např. tady jsem se na chvíli zastavil a přemýšlel, odkud `PC` pochází. Co bys řekl na pojmenování `ProjectCardComponent` namísto `PC`?

2021-03-07 19:58 UTC, HormCodes commented on locale/translation.example.json
> +  "pages": {
Vím, že toto navazuje na diskusi na Slacku. Ještě nad tím trochu uvažuji, zda klíče do example přidávat nebo ne. Vypadá to spíše, že ano, ale rád bych to provedl cestou přidání všech najednou jako jeden commit spolu s informativním textem do README. Můžeš tedy prozatím prosím tyto změny (klíče a také generované typy) odstranit?

2021-03-07 21:44 UTC, maral commented
Změny zapracovány, myslím, že je to ready. Možná ještě rebase na konsolidaci commitů. Jak jsem psal o tom double scrollbaru, tak to se děje pouze když je tam ten translate klíč dlouhý, že přesahuje na stranu, protože v komponentě Section je overflow: auto; Myslím, že to je tak správně, byť to bez překladů vypadá blbě.

2021-03-08 09:40 UTC, HormCodes commented
@maral, myslím tento padding...

![web-git-fork-maral-our-projects-ceskodigital vercel app_(iPhone 5_SE)](https://user-images.githubusercontent.com/10332399/110303380-9c8d7580-7ffa-11eb-8a5d-265a51740a76.png)

2021-03-08 09:40 UTC, HormCodes commented
@maral, myslím tento padding...

![Screenshot 2021-03-08 at 10 39 13](https://user-images.githubusercontent.com/10332399/110303459-b3cc6300-7ffa-11eb-9da8-6ee23c25f83a.png)

2021-03-08 15:09 UTC, tjerabek approved these changes
Za mě super. Ten zmíněný padding bych neřešil a nechal tak, jak je. Díky!

2021-03-08 15:11 UTC, maral commented
Já to ještě opravím, původně jsem to měl přes flex, tam jsem to měl správně dle návrhu, ale pak po předělání do CSS gridu jsem na to zapomněl.

2021-03-08 17:36 UTC, maral commented
Opraveno, je tam použitý trik s double gridem, protože jinak overflow v CSS gridu uřezává veškeré paddingy a marginy napravo: https://stackoverflow.com/questions/46130586/css-grid-scrolling-issue-right-side-padding-and-border-overlapping-content/46130659

2021-03-14 15:50 UTC, HormCodes approved these changes
@maral, díky moc za úpravy a ještě jednou za pull request. 🙏 

Nakonec jsem se rozhodl sekci vytáhnout a rovnou ji umístit i na stránku projektu. 

V každém případě dobře odvedená práce. 👍

2021-03-14 15:50 UTC, merged