Hero header
cesko-digital/web pull request #183
Opened 2021-03-15 16:04 UTC by jirizikes

Fixes # .

Checklist pro nové změny:

- [ ] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [ ] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [ ] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [ ] Veškerá logika má jednoduché pokrytí unit testy
- [ ] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [ ] Design odpovídá Figmě
- [ ] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [ ] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-03-15 16:18 UTC, tuanphungcz requested changes

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/index.tsx
> +          <S.image4 />
Navrhnul bych nazev, ktery je vice vypovidajici napriklad `HeroTeamCircleImage`?

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/index.tsx
> +
smazat mezeru

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/index.tsx
> +      <S.Circle />
Mozna bych ten Circle aby bral `color` jako prop a pak muzem posilat zlutou barvu a tu fialovou?

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +  overflow: hidden;
u tech css se snazime dodrzovat ty media queries na konci a mezi. Navrhoval takto: 

```
export const Container = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: ${({ theme }) => `${theme.space.md}px ${theme.space.md}px`};
  height: 602px;
  position: relative;
  overflow: hidden;

  @media (max-width: ${({ theme }) => theme.breakpoints.lg}) {
    grid-template-columns: 1fr;
    height: 530px;
  }
```

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +
smazat mezeru

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +
smazet mezery

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +
smazat mezeru

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +
smazat mezeru

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +  background: #fff6a3;
udelal abychom mohli posilat color jako prop a bude se to hodit na to fialovy kolecko
```
 background: ${(props) => props.color} || `#fff6a3`;
```

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +
smazat mezeru

2021-03-15 16:18 UTC, tuanphungcz commented on src/page-components/homepage/sections/numbers/index.tsx
> +import { Section, SectionContent } from 'components/layout'
unused Section

2021-03-15 16:22 UTC, tuanphungcz commented
![image](https://user-images.githubusercontent.com/16448321/111186031-e5bd6680-85b2-11eb-93ff-696874519c59.png)

na nekterym breakpointu chybi margin mezi tlacitky

2021-03-17 12:15 UTC, tuanphungcz requested changes

2021-03-17 12:15 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +  margin-bottom: 32px;
jeste bych doplnil tyto veci podle designu: 
```
line-height:32px
color:  ${({ theme }) => theme.colors.asphalt} 
```

2021-03-17 12:15 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +import heroImg1 from 'images/hero-img-1.png'
mozna bych misto heroimg1,3,4 bych  dal nejaky nazev co je vice vypovidajici? Pokud k tomu prijde nekdo dalsi, tak nevi co ty cisla znamenaji, Treba podle velikosti tech kolecek? nebo podle toho jak si pojmenoval ty styled komponenty

v nasem pripade treba ?
```
hero-image-circle-sx,
hero-image-circle-1-sm,
hero-image-circle-2-md
```

2021-03-17 12:15 UTC, tuanphungcz commented on src/page-components/homepage/sections/hero/styles.ts
> +  margin-bottom: 32px;
https://www.figma.com/file/8YdGIHXLPo8zt4ZN8KJ4Hy/%3EC.D-%2F-Web?node-id=5%3A5108
![image](https://user-images.githubusercontent.com/16448321/111465882-e2e18380-8722-11eb-9de0-23ce99af9340.png)

2021-03-17 13:56 UTC, tuanphungcz approved these changes

2021-03-17 13:57 UTC, tuanphungcz commented
@tjerabek je to ready na design-review

2021-03-22 16:36 UTC, tjerabek approved these changes
LGTM

2021-03-22 16:40 UTC, merged