Feature/newsletter api
cesko-digital/web pull request #191
Opened 2021-03-18 22:07 UTC by rostaklein

- fixes https://github.com/cesko-digital/web/issues/156
- closes https://github.com/cesko-digital/web/pull/167

Musel jsem vytvorit nove PR, to puvodni je na privatnim forku.

Jednotlive zmeny popsany v commitech.

Veci kteryma si nejsem jisty:
- jak vyresit replace emailu v translation v successful submit state
- jestli ma cypress testovat i serverless funkci (tady by me fakt zajimalo jestli/jak/proc to udelat)

2021-03-22 14:48 UTC, tuanphungcz commented on src/components/layout/footer/newsletter-form/styles.tsx
> +    background-image: url("data:image/svg+xml,%3Csvg width='24' height='24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M20 6L9 17l-5-5' stroke='%23062' stroke-width='2' stroke-lineca
@rostaklein zajimalo by me proc si nedal prednost pouzit ikonu jako background image s absolute position misto vlozit checked ikonu jako komponetu a vycentrovat skrze `display: flex`?

2021-03-22 14:48 UTC, tuanphungcz commented on src/components/layout/footer/newsletter-form/validations.ts
> +    if (!/^\S+@\S+\.\S+$/.test(email)) {
mame jeste jeden regex v `api/newsletter`. Mozna bychom to meli sjednotit a pouzit stejny regex pattern

2021-03-22 21:02 UTC, tuanphungcz commented
@rostaklein Ahoj, diky za pull request. Co se tyce cypress testu, tak takhle nam to staci. Na testovani serverless funkce pak nastavime logovani, kdyby to nefungovalo. Jinak co presne si myslel tim `replace emailu v translation v successful submit state` ?

2021-03-26 12:56 UTC, tuanphungcz commented
@rostaklein Poprosim vlozit screenshot jak vypada success box po vlozeni emailu. Diky 👍

2021-03-26 12:56 UTC, tuanphungcz approved these changes

2021-03-26 17:19 UTC, tuanphungcz commented
![image](https://user-images.githubusercontent.com/16448321/112669273-cd293800-8e5f-11eb-924c-ba5b277b91e5.png)

2021-03-26 17:19 UTC, tuanphungcz commented
@tjerabek Predavam dal na design-review

2021-03-29 07:17 UTC, tjerabek requested changes
Přidal bych nějaký in progress stav. Když jsem zadal email, po kliknutí to působilo, že se nic neděje.

2021-03-29 07:59 UTC, rostaklein commented
> Přidal bych nějaký in progress stav. Když jsem zadal email, po kliknutí to působilo, že se nic neděje.

Jak by mel vypadat? :) Mam neco vymyslet? Koukam, ze button zadny loading state by default nepodporuje.

2021-03-29 08:01 UTC, tuanphungcz commented
Co bych navrhoval jako nejsnadsi cesta je udelat input a tlacitko disabled pri onSubmitting, tak aspon omezime usera aby znova klikal nebo editoval formulari pri posilani API.

cc @HormCodes co myslis?

2021-03-29 10:57 UTC, tuanphungcz commented
@rostaklein Pokud je form submitting, mimo disabled input+button pri odesilani prosim upravil taky label tlacitka z `Odebirat` na `Registruji`

2021-03-29 14:55 UTC, HormCodes commented
Jojo, disable + změna labelu je asi nejjednodušší řešení. Pokud bys chtěl, tak si taky dokáži představit rozšíření tlačítka o prop `loading`, který by nahradil text za loading spinner. 🤔

2021-04-02 19:25 UTC, rostaklein commented
Hele kluci od pondeli budu dost mozna minimalne tyden mimo dosah PC, takze bychom to mohli posunout 😉

2021-04-04 11:35 UTC, tuanphungcz commented
@rostaklein cau, zkusis jeste jednou rebase `rework` aby tam byl tento [commit](https://github.com/cesko-digital/web/commit/5f6dcc816ae2fcffab8d98b53b956917af55a6db) a snad by mohl uz projit build. Dale jestli bys to mohl svoje commity squashnout do 1. Diky

2021-04-09 09:02 UTC, tuanphungcz commented
@tjerabek Ahoj, uz tam mame loader, poprosim o quick review

2021-04-09 10:12 UTC, merged