Fix #360
cesko-digital/web pull request #388
Opened 2021-11-25 18:24 UTC by l-korous

Fixes https://github.com/cesko-digital/web/issues/360 .

Checklist pro nové změny:

- [ ] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [ ] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [ ] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [ ] Veškerá logika má jednoduché pokrytí unit testy
- [ ] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [ ] Design odpovídá Figmě
- [ ] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [ ] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2021-11-26 09:45 UTC, zoul requested changes
Obecně k designu: Navrhuju použít stejnou velikost písma jako u těch hashtagů pod názvem eventu, víc zaoblit rohy (viz Figmu) a maličko přidat padding – ale to případně klidně můžu doladit.

A přemýšlím nad tím, jak zařídit, aby tyhle nové informace nepřetekly na dva řádky, protože pak nám nesedí nadpisy a vypadá to blbě:

![sshot](https://user-images.githubusercontent.com/95329/143560597-cc597976-a9b9-45e5-a09b-fec566cf892e.png)

Za mě je klidně přijatelné krátit ten text, pokud se nevejde na jeden řádek – jde to?

Díky moc!

2021-11-26 09:45 UTC, zoul commented on src/page-components/portal-dobrovolnika/event-card/index.tsx
> +          {locationTitle && locationTitle !== '' && (
Tady asi může být jen `locationTitle && …`? Prázdný řetězec je „falsy“.

2021-11-26 09:45 UTC, zoul commented on src/utils/get-relative-date.ts
> +      const tomorrowDate = new Date(nowDate)
Doporučuju nikdy neformátovat data a časy ručně, je to jedno velké klubko hadů :) Obecně platí, že s daty a časy je lepší dělat co nejvíc přes nabízená API, aby se člověk nespálil (off-by-one chyby, přestupné roky, změny času, časové zóny, etc). Silné povahy mohou nahlédnout [sem](https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca) :) Takže tady asi doporučuju `Date.toLocaleString`, kde jsou nějaké vhodné presety.

A celkově je tohle výborný kandidát na pár unit testů? Přičemž (nejen) v rámci testů je dobré nečíst aktuální datum uvnitř funkce (`nowDate = new Date()`), ale předat ho jako parametr s výchozí hodnotou. Tak se pak dá v testech snadno poslat předem známá hodnota „now“.

2021-11-26 11:37 UTC, l-korous commented on src/utils/get-relative-date.ts
> +      const tomorrowDate = new Date(nowDate)
unit testy - souhlas

toLocaleString - zejména pokud chceme mít kontrolu nad tím jak je ten text dlouhý (viz ten bod že když je to celé na dva řádky, je to problém) - nemyslím si; jednak uživatelé jsou ze sta procent schopni pochopit tento datumový formát, a ostatní věci (přestupné roky, ...) tady nejsou problém - můžeš uvést konkrétní problém prosím?

2021-11-26 11:37 UTC, l-korous commented on src/page-components/portal-dobrovolnika/event-card/index.tsx
> +          {locationTitle && locationTitle !== '' && (
OK :-)

2021-11-26 11:38 UTC, l-korous commented
zkusím zkrátit text nějak tedy ;-)

2021-11-26 12:33 UTC, zoul commented on src/utils/get-relative-date.ts
> +      const tomorrowDate = new Date(nowDate)
Nejde o to, že by ten formát byl nesrozumitelný nebo že by ten kód byl špatně. Ale je to špatný příklad, jako řezat na cirkulárce rukou blízko kotouče. Ty třeba víš, co děláš, ale odkouká to od tebe někdo druhý, kdo už to vědět nebude, a uřízne si prsty. Proto mně přijde lepší používat v těchto citlivých případech důsledně to „správné“ řešení, v tomhle případě formátovací API. Viz třeba:

```javascript
new Date().toLocaleString('cs-CZ', {month: "numeric", day: "numeric", "hour": "2-digit", minute: "2-digit"})
"26. 11. 13:28"
```

To je cajk, ne?

2021-11-26 13:27 UTC, zoul commented
(Přehodil jsem PR na draft, ať líp vidíme, co je _ready to merge_.)

2021-11-26 18:50 UTC, l-korous commented on src/utils/get-relative-date.ts
> +      const tomorrowDate = new Date(nowDate)
Už to tak dělám, jen je podle mě škoda že tam ta funkce přidá mezeru - zbytečně to zabírá místo, osobně se mi to nelíbí a je to podle mě i nestandardní - díval jsem se na pár stránek (cnb.cz, mpo.cz) pro inspiraci a taky tam nemají mezeru. Vzhledem k tomu že to stejně stavím separátně pro datum a pro čas a navíc chci dávat podmíněně rok, tak by to vypadalo v kódu takto:

`...
toReturn = startDate.toLocaleString('cs-CZ', {month: 'numeric', day: 'numeric'});
        if (startDate.getFullYear() !== nowDate.getFullYear())
          toReturn += ' ' + startDate.getFullYear()
      }
    }

    toReturn += ', ' + startDate.toLocaleString('cs-CZ', {hour: '2-digit', minute: '2-digit'});
...`

což taky není žádná paráda, takže bych tam s dovolením asi přeci jen nechal to že si ten string postavím sám.

co myslíš? Hlavně ta mezera mě tam dráždí

2021-11-26 19:51 UTC, l-korous commented
unit test přidán, úpravy udělané - mrkni prosím @zoul

2021-11-29 11:31 UTC, zoul commented on src/utils/get-relative-date.ts
> +      const tomorrowDate = new Date(nowDate)
Koukal jsem na tu mezeru a [Pravidla připouští obě možnosti](https://prirucka.ujc.cas.cz/?id=810), přičemž jako obvyklejší mně (i z těch pravidel) přijde varianta s mezerou. Ještě je pro mě důležité, aby to bylo na celém webu stejně, což by opět nahrávalo použití toho standardního API s minimem ručních zásahů (které každý udělá trochu jinak) – viz třeba [detail události](https://cesko.digital/events/show-and-tell-8), kde datum a čas máme taky.

Já to každopádně mergnu a pokud nebudeš vysloveně proti, můžu to formátování poštelovat ex post.

2021-11-29 11:32 UTC, merged