Fix routing - all routes in czech
cesko-digital/web pull request #410
Opened 2021-12-22 17:23 UTC by l-korous

Některé routy byly česky, jiné anglicky. Myslím že i kvůli SEO je dobré je mít česky.

Checklist pro nové změny:

- [ ] Kód je v souladu s [Contribution Guidelines](../CONTRIBUTING.md)
- [ ] Nové vizuální komponenty jsou ve Storybooku včetně dokumentace jejich rozhraní
- [ ] HTML je semanticky správně strukturované (headings, odstavce, seznamy atd.)
- [ ] Nové závislosti není možné nahradit vlastní jednoduchou implementací, jsou pod správnou open source licencí a [jejích velikost je přijatelná](https://bundlephobia.com/)
- [ ] Veškerá logika má jednoduché pokrytí unit testy
- [ ] Ilustrace a ikony jsou vloženy jako [React SVG komponenta](https://react-svgr.com/playground/)
- [ ] Design odpovídá Figmě
- [ ] Změny byly krátce otestovány v Chrome, Safari, případně dalších prohlížečích
- [ ] Git log neboli historie commitů je čistá (rozdělení do více commitů je možné pokud se jedná o odlišný kontext změn, např. nutný refactoring něčeho jiného)

2022-01-05 17:04 UTC, zoul commented
Super, tohle určitě chceme, díky! Jak jsem mergnul přepis do masteru, hodně se to rozjelo. Uděláš prosím rebase nad aktuální master? A druhá věc – mrkneš prosím na přesměrování ve `vercel.json`, abychom přesměrovali ta původní URL?

2022-01-13 16:11 UTC, l-korous commented
Mrknu na to, nějak jsem byl rozlítaný po svátkách, ale už budu zase k dispozici :-)

2022-01-18 10:26 UTC, l-korous commented
Po diskuzi v https://github.com/cesko-digital/web/issues/434 předěláno na angličtinu

2022-01-19 09:53 UTC, karmi approved these changes
Za mně dobrý, moc díky!

2022-01-19 10:51 UTC, zoul requested changes
Nechal jsem pár poznámek, ale především nám teď chybí přesměrování cesty `/projekty/:id` na nové URL, takže by nám nefungovalo například https://cesko.digital/projekty/ucime-online. Můžeš prosím Lukáši mrknout, jestli jde tohle zařídit ve `vercel.json`? Děkuju!

2022-01-19 10:51 UTC, zoul commented on components/layout/footer/index.tsx
>      [p.projects, "/projekty"],
Tady by IMO mělo být `/projects`. Ale především by to tady nemělo být hard-coded, měli bysme tu použít `Route.projects`, a tím se opraví i ta chyba. (Podobně odkaz na blog by měl být `Route.blog`.) Opravíš, prosím?

2022-01-19 10:51 UTC, zoul commented on pages/events/[slug].tsx
> +        { path: "/dashboard", label: "Portál dobrovolníka" },
Ideálně ale `Route.volunteerPortal`? (Snažíme se zařídit, aby ty routy byly na jednom místě a daly se snáz měnit.) A případně můžeš `Route.volunteerPortal` přejmenovat na `Route.dashboard`, ať je to konzistentní.

2022-01-19 10:51 UTC, zoul commented on pages/events/[slug].tsx
> +              <Link to="/dashboard">Všechny příležitosti</Link>
Ideálně `Route.volunteerPortal`.

2022-01-19 10:51 UTC, zoul commented on pages/opportunities/[slug].tsx
> +        { path: "/dashboard", label: "Portál dobrovolníka" },
Ideálně ty cesty přepsat na `Route.volunteerPortal` a `Route.opportunities`?

2022-01-19 10:51 UTC, zoul commented on vercel.json
> +      "destination": "http://cesko.digital/dashboard",
Může tu být relativní URL? Pokud jo, tak by mělo být.

2022-01-19 21:13 UTC, l-korous commented
@zoul , mělo by to být všechno jak píšeš:

- přesměrování i pro /projects/:id
- použití Route z lib/routing místo hard-coded stringů
- relativní linky
- Route.dashboard místo Route.volunteerPortal

Mrkni prosím

2022-01-20 08:03 UTC, zoul approved these changes
Krása! Díky moc, Lukáši, žes s tím přišel a dotlačil to do konce 🚀

2022-01-20 08:03 UTC, merged