Do not render open in slack if the provided url is invalid.
cesko-digital/web pull request #554
Opened 2022-03-28 19:47 UTC by pionl

Více zde #553

- Připravil jsem základní test komponenty po refactoringu - do budoucna kdo bude mít čas může přidat další "testy"
- ošetřil jsem různé invalidní hodnoty na contactUrl (můžeme odebrat možná undefined / null)

2022-03-29 11:46 UTC, zoul requested changes
Supr! Akorát ten `resolver` už je na mě overkill, pojďme tam ve všech případech prostě nechat popisek `Kontaktovat` a můžeme se zbavit jak toho resolveru, tak testů komponenty? Čím míň kódu, tím líp :)

2022-03-29 11:52 UTC, pionl commented
> Supr! Akorát ten `resolver` už je na mě overkill, pojďme tam ve všech případech prostě nechat popisek `Kontaktovat` a můžeme se zbavit jak toho resolveru, tak testů komponenty? Čím míň kódu, tím líp :)

Nedokážu posoudit, nepřipadá mě to že by to mělo mít dopad na údržbu, je to dost malé. Z pohledu uživatele si myslím, že `Kontaktovat` je špatně. Takto uživatel ví co výchozí tlačítko kontaktovat znamená. Například `Slack` ne každý použije a radši zvolí email který je většinou v textu.

Je třeba "potvrzení" od někoho jiného nebo to mám odebrat?

2022-03-31 12:05 UTC, zoul commented
Tak pojďme ty dynamické popisky kontaktního tlačítka nechat; souhlasím, že je to lepší textace. Ale ta implementace i testy můžou být výrazně jednodušší. Udělejme prostě funkci, která vrátí vhodný popisek pro dané URL? Něco na způsob:

```typescript
type ContactButtonLabel = "Kontaktovat přes Slack" | "Kontaktovat mailem" | "Kontaktovat";
function contactButtonLabelForUrl(url: URL): ContactButtonLabel { … }
```

Tím pádem ty testy můžou být výrazně kratší, zbavíme se toho dlouhého testu celé komponenty. Co myslíš? Díky!

2022-03-31 15:06 UTC, pionl commented
O víkendu se na to podívám. Testy teda mírně zredukuji nějak rozumně

2022-04-22 15:18 UTC, zoul commented
Vyřešeno v #574.

2022-04-22 15:18 UTC, closed without merging