fix(theme): contain values in objects instead of arrays
cesko-digital/web pull request #80
Opened 2020-10-28 15:12 UTC by Erbenos

Nové hodnoty pro fontSizes jsou hodnoty vzaté z Figmy.

2020-10-28 17:35 UTC, fidelman commented on src/theme/default/index.js
> +    xxxl: '44px',
muze bit drzet jako `number`? 
```suggestion
    xxxl: 44,
```

2020-10-28 20:20 UTC, Erbenos commented on src/theme/default/index.js
> +    xxxl: '44px',
Máš to tam.

2020-10-31 14:18 UTC, HormCodes approved these changes
Ze mne OK. 🙂

2020-10-31 14:20 UTC, HormCodes requested changes
Akorát nám tady vznikl konflikt, mohu poprosit o rebase? Poté zamerguji.

2020-10-31 14:58 UTC, Erbenos commented
Zbavil jsem to konfliktu.

2020-10-31 15:02 UTC, HormCodes approved these changes

2020-10-31 15:04 UTC, merged