feat(design): footer component
cesko-digital/web pull request #98
Opened 2020-11-22 19:42 UTC by Erbenos

Nevím jestli je třeba Storybook i pro komponenty bez parametrů, tak případně někdo prosím pípněte.

Musel jsem trochu porušit enkapsulaci odkazů, protože nemáme bílé Link-y.

Laptop mám teď v servisu 😭, tak nebudu moc být tak flexibilní s adresací případných problému, jak bych chtěl.

2020-11-25 15:48 UTC, HormCodes requested changes
Ahoj @Erbenos, vypadá to velmi dobře. Líbí se mi, jak už konečně začiná vznikat něco, na co se dá koukat. A byla radost PR procházet. 👍 

Přidal jsem několik komentářů ke kódu, snad je všechno srozumitelné. Ale jinak velmi dobře odvedená práce a těším se, až to zamergujeme. 🙂

2020-11-25 15:52 UTC, HormCodes commented
Fixes #75

2020-11-25 16:44 UTC, HormCodes commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Máme výstup: Bylo by možné zde využít React state a implementovat jednoduché validace pro formulář? Navrhuji využít https://formik.org/ a validaci pokrýt Jest testem.

2020-11-25 18:04 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Links = styled.div`
Moc jsem sémantice nevěnoval pozornost, obalím to ještě <nav> -em.

2020-11-25 18:08 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +const flexGapPolyfill = (gap: number): string => `
Kdybych neincludnul ten polyfill, nefungovalo by to v Edgi, ktery je vychozi browser v ciste Windows 10 instalaci. Zkousel jsem to v Chromu a tam. Alternativa k gap-u by byl treba margin se sibling selektory, neni to uplne stejne, ale v tomhle use case otazka preference.

2020-11-25 18:08 UTC, Erbenos commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Jasne, np

2020-11-25 18:14 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +const flexGapPolyfill = (gap: number): string => `
Rozdil popsany bud na MDN nebo quick google search vratil https://coryrylan.com/blog/css-gap-space-with-flexbox

2020-11-25 18:14 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Heading = styled.h4`
Jasne klidne tam dam h2. Nerozumim h1 komentari.

2020-11-25 18:15 UTC, Erbenos commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Knihovna na formulare kvuli jednomu vstupu mi prijde jako dost overkill, ale bude na eebu vice komplexnejsich formu klidne, je to na vas.

2020-11-25 18:15 UTC, Erbenos commented on src/components/site-footer/index.tsx
> +    footnote: 'cesko.digital © 2020, Tento web používa cookies ¯_(ツ)_/¯',
Jasne, diky za note, detail

2020-11-25 18:17 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Outer = styled.footer`
Na designu mrknu a upravim

2020-11-25 18:20 UTC, Erbenos commented
Cekam laptop do tydne, uz je fixly, musim jej jen dostat zpet.

2020-11-30 13:35 UTC, HormCodes commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Formik nemusí být použit, ale React state s validací ano. Jsme si vědomi, že je to trochu overkill, ale v rámci PoC se jedná o trochu o prezentaci práce na klientské straně.

2020-11-30 13:37 UTC, HormCodes commented on src/components/site-footer/styles.ts
> +export const Heading = styled.h4`
Teoreticky může existovat stránka např. `O nás`, která bude obsahovat pouze nadpis a pak odstavce. V rámci struktury pak dává aby patička využívala `h2` jako druhou úroveň nadpisu.

2020-11-30 13:41 UTC, HormCodes commented on src/components/site-footer/styles.ts
> +const flexGapPolyfill = (gap: number): string => `
Ano vzhledem k tomu, že se bude jednat pouze o mezery mezi `li` si myslím, že bych využil standardní `margin`

2020-12-01 18:00 UTC, Erbenos commented
Až budou všechny připomínky pořešené, tak to squashnu.

2020-12-01 18:00 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Outer = styled.footer`
Adresováno d8a2b65

2020-12-01 18:11 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Links = styled.div`
Adresováno 09c427e

2020-12-01 18:20 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +const flexGapPolyfill = (gap: number): string => `
Actually, gap pěkně řešil mezery mezi link sekcemi - nemusel předefinovávat margin, když mi na nižších rozlišení začaly vertikálně stackovat. To ale dle nového designu pro mobily stejně nebudou. Just FYI. 

Adresováno a61fae1

2020-12-01 18:23 UTC, Erbenos commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Všiml jsem si, že to používám to na pozadí <div>, upravdu to chceš do té komponenty a přestylovat to?

2020-12-01 18:24 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Heading = styled.h4`
To je ale si myslím u HTML5 irelevantní, protože <footer> dostává svůj vlastní outline. Klidně můžeš mít více nadpisů.

2020-12-01 18:27 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Heading = styled.h4`
Adresováno h4 -> h2 01f7cc1

2020-12-01 18:29 UTC, Erbenos commented on src/components/site-footer/index.tsx
> +    footnote: 'cesko.digital © 2020, Tento web používa cookies ¯_(ツ)_/¯',
Adresováno 2223652

2020-12-01 20:02 UTC, Erbenos commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Adresováno 6f7dc48

2020-12-01 20:06 UTC, Erbenos commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Ještě jsem zapomenul na ten test.

2020-12-08 17:23 UTC, HormCodes commented on src/components/site-footer/index.tsx
> +            action={`https://ceskodigital.ecomailapp.cz/public/subscribe/${listID}/${accID}`}
Založím nové vlákno k novému kódu.

2020-12-09 10:02 UTC, HormCodes commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Neexistuje alespoň cesta jak obrázek importovat do background elementu v rámci styled components přes TS import?

2020-12-09 10:04 UTC, HormCodes commented on src/components/layout/footer/styles.ts
> +export const Outer = styled.div`
Ještě jeden požadavek v rámci designu, bylo by možné upravit styly patičky (a layoutu) tak, aby při malých stránkách nebylo pod patičkou bílá barva, ale modrá?

2020-12-13 17:55 UTC, Erbenos commented on src/components/layout/footer/styles.ts
> +export const Outer = styled.div`
Adresováno d3125af

2020-12-13 18:11 UTC, Erbenos commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Ano, musel bych v nějakém `*.d.ts` souboru nadefinovat všechny *.jpg, *.png apod. jako moduly. Což mi ale přijde jen jako další vrstva abstrakce jejíž výhody mi nejsou zřejmé, nad tím, co mám již teď. See https://github.com/microsoft/TypeScript-React-Starter/issues/12

2020-12-13 19:09 UTC, Erbenos commented on src/components/site-footer/styles.ts
> +export const Outer = styled.footer`
Mobilní verze a6dec9a

2020-12-13 22:44 UTC, Erbenos commented on src/components/layout/footer/index.tsx
> +  const [email, setEmail] = useState('')
Abstrahoval jsem logiku formulářu do hooku v a5e7ba1. Abych mohl submittovat přes Ajax do ecomailu, bude nejspíše třeba API klíč (a jeho následné vložení něka do env proměnných v build procesu). https://intercom.help/ecomail/cs/articles/66536-api-pro-praci-s-ecomailem . Nemám k tomu teď přístupy.

2020-12-14 16:47 UTC, HormCodes commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Ano, zadefinování typu je bohužel nutné (jedna z nevýhod TS v případě Reactu). Použití přes import je bezpečnější pokud jde o změny. 

V případě, že se použije `background-image: url(${importedImage});` a někdo omylem odstraní obrázek, tak neprojde Gatsby build. V případě klasického řetězce a assets ano. 

Sám jsem si původní cestou mnohokrát způsobil trable a překvapení, že něco nefunguje.

2020-12-14 20:54 UTC, Erbenos commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Adresováno fcf021e

2020-12-16 15:47 UTC, HormCodes commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Super, rozhodně krok kupředu. Za mne není potřeba alias na `static` složku a je lepší mít PNG v `src/images` a SVG React komponenty v `src/components/icons`. 

Gatsby funguje tak, že pro importované PNG vygeneruje obrázek ve static složce a do CSS/komponenty pošle přiíslušnou URL, takže v případě `<img src={importedImage} />` lze aplikovat stejné věci typu lazy loading atd.

2020-12-16 15:59 UTC, HormCodes commented on src/components/layout/footer/index.tsx
> +  const [email, setEmail] = useState('')
API klíč nelze mít s rozsahem pouze pro subscribe, takže budeme muset klíč zakrýt přes vlastní API endpoint. Vytvořil jsem na to issue (#107) a musím promyslet, jakým způsobem to prioritizovat. Dám update během dnešního dne ještě. 

Pokud jde o samotný hook, tak rozhodně krok dopředu, ale ještě tam vidím prostor pro zlepšení a je možné, že jsme se vzájemně nepochopili. 

Cíl ani tak není mít obecné řešení pro formuláře (to můžeme vyřešit přidáním Formiku) jako spíše vytvoření pevně definovaného rozhraní pro formulář patičky. Jde o to, že by mělo být na první pohled jasné, jaké hodnoty jsou součástí formuláře a bezpečný způsob pro kontrolu formuláře (např. při použití Formiku se nevyužívá `[setFieldValue](https://formik.org/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void)`, ale logika se zanoří do `handlers.emailChange: (event) => setFieldValue('email', event.target.value)`. 

Pokud je to stále nejasné, možná bude lepší si kolem toho zavolat. Vím, že to bude další nutná změna, ale stále platí, že tímto formulářem určujeme vzor pro další, které rozhodně budou přibývat.

2020-12-16 20:02 UTC, Erbenos commented on static/assets/footer-mail.svg
> +<svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Adresováno 9648647

Vzhledem k tomu, že to mám ten vektor v backgroundu (jistě by to šlo překódovat, kdyby šlo na lámání hole), tak to nechám v src/images, ale jinak bych to dal do React komponenty jak zmiňuješ.

2020-12-16 20:23 UTC, Erbenos commented on src/components/layout/footer/index.tsx
> +  const [email, setEmail] = useState('')
Jak jsme se domluvili přes Slack/GMeet, všechno ohledně formuláře jsem purgnul 07b3d49

2020-12-16 20:38 UTC, Erbenos commented on src/components/layout/footer/index.tsx
> +  const [email, setEmail] = useState('')
Ještě ten hook....

2020-12-16 20:53 UTC, Erbenos commented on src/components/layout/footer/index.tsx
> +  const [email, setEmail] = useState('')
7159ade

2020-12-16 20:54 UTC, Erbenos commented
Rebasnul jsem na master, kontrola, squashnu to, a jsme done.

2020-12-18 11:11 UTC, merged